FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y git \
                    bash \
                    sudo \
                    git \
                    wget \
                    flex \
                    bison \
                    gperf \
                    python3 \
                    python3-pip \
                    python3-venv \
                    cmake \
                    ninja-build \
                    ccache \
                    libffi-dev \
                    libssl-dev \
                    dfu-util \
                    libusb-1.0-0

